import Head from "next/head";
import React from "react";
import AlphaLogoWithShadow from "../src/components/branding/AlphaLogoWithShadow/AlphaLogoWithShadow";
import IntroText from "../src/components/branding/IntroText/IntroText";
import LoadScreen from "../src/components/LoadScreen/LoadScreen";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Home from "../src/components/Home/Home";

export default function HomePage() {
  const [loading, setLoading] = React.useState(true);
  const [loadingAnimationComplete, setLoadingAnimationComplete] =
    React.useState(false);

  const [showIntro, setShowIntro] = React.useState(false);
  const [introComplete, setIntroComplete] = React.useState(false);

  const setLoadingTimeOut = (timeout) => {
    setInterval(() => {
      setLoading(false);
    }, timeout);
  };

  const setIntroTimeOut = (timeout) => {
    setInterval(() => {
      setShowIntro(false);
    }, timeout);
  };

  React.useEffect(() => {
    setLoadingTimeOut(5000);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Arsh Sekhon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <AlphaSpinner />*/}
        {!loadingAnimationComplete && (
          <LoadScreen
            loading={loading}
            setLoadingAnimationComplete={() => {
              setLoadingAnimationComplete(true);
              setShowIntro(true);
              setIntroTimeOut(2000);
            }}
          />
        )}
        {loadingAnimationComplete && !introComplete && (
          <IntroText
            showIntro={showIntro}
            setIntroComplete={() => {
              setIntroComplete(true);
            }}
          />
        )}
        {/* <div>
          <IntroText />
          
        </div> */}
        {introComplete && <Home />}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
