import Head from "next/head";
import Image from "next/image";
import React from "react";
import AlphaLogoWithShadow from "../src/components/branding/AlphaLogoWithShadow/AlphaLogoWithShadow";
import AlphaSpinner from "../src/components/branding/AlphaSpinner/AlphaSpinner";
import LoadingText from "../src/components/LoadingText/LoadingText";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <AlphaSpinner />
          <LoadingText />
        </div>

        <div>
          <AlphaLogoWithShadow />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
